export default function Home() {
  return (
    <main>
      <h3>What this does</h3>
      <p>
        Configure topics + sources, choose a frequency, and get an email newsletter generated by an agent.
      </p>
      <ul>
        <li><a href="/settings">Go to Settings</a></li>
        <li><a href="/history">View History</a></li>
      </ul>
    </main>
  );
}
